on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests inside Docker container
        run: |
          docker build -t my-image:${{ github.sha }} .
          docker run --rm -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}  -e AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }} my-image:${{ github.sha }}
        continue-on-error: false

      - name: Build and Push Docker Image
        if: success()  
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}  
        run: |
          # Build Docker image from the present Dockerfile, tagging it with the current commit SHA
          docker build -t my-image:${{ github.sha }} .

          # Login to Amazon ECR
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 376129872445.dkr.ecr.us-east-2.amazonaws.com

          # Tag the Docker image to match ECR repository format
          docker tag my-image:${{ github.sha }} 376129872445.dkr.ecr.us-east-2.amazonaws.com/my-image:${{ github.sha }}

          # Push the Docker image to ECR
          docker push 376129872445.dkr.ecr.us-east-2.amazonaws.com/my-image:${{ github.sha }}

