on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests inside Docker container
        run: |
          docker build -t my-image:${{ github.sha }} .
          docker run --rm -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}  -e AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }} my-image:${{ github.sha }}
        continue-on-error: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-image:${{ github.sha }} .

      - name: Save Docker image to tar file
        run: |
          docker save my-image:${{ github.sha }} -o my-image.tar

      - name: Upload image tar file to repository
        run: |
          mkdir -p artifacts
          mv my-image.tar artifacts/my-image-${{ github.sha }}.tar
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git add artifacts/my-image-${{ github.sha }}.tar
          git commit -m "Add Docker image tarball"
          git push origin main

