on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests inside Docker container
        run: |
          docker build -t my-image:${{ github.sha }} .
          docker run --rm -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}  -e AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }} my-image:${{ github.sha }}
        continue-on-error: false

      - name: Merge pull request
        if: success()  
        uses: peter-evans/merge-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash  
          commit-message: "Automatically merged after successful build and push"
