on: workflow_dispatch
  ## YOUR CODE HERE: modify the above line (and possibly other places) to execute this action only on merged PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      ## YOUR CODE HERE: create step to execute same tests as test.yaml before building.
      - name: build and push
        ## YOUR CODE HERE: execute this step only if previous step passes
        env:
          ## YOUR CODE HERE: Import AWS Credentials as env variables
        run: |
        ## YOUR CODE HERE: Build image from present Dockerfile. Tag with current commit_id
        aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 376129872445.dkr.ecr.us-east-2.amazonaws.com
        ## YOUR CODE HERE: Push image

          
